### ISSUE TITLE
Folder created during recording game Space Marine 2

### ISSUE THREAD

**Issue by zhbanok** [Penwy/adv-ff#6]
Discovered new problem when recording Warhammer 40,000: Space Marine 2

For each record in main folder created new folder like this:
**Record 2024-09-14 12-55-19 [Warhammer 40,000_ Space Marine 2 CLIENT 2.1.DAY2.342812**
and there are recorded file **343200].mp4** inside.

**Formatting for records:** Replay%CCYY-%MM-%DD %hh-%mm-%ss [v$1[title]$]

**Comment by Penwy** [comment]
So, the issue here is that the window title of space marine 2 has a slash in it, which is what creates a folder. That's not a bug, the ability to create subfolders like that is part of the base functionality of it in obs.
You have two options here :
- `v$1[executable]$` : exe names are far more sanitized and will not ever contain a slash (or 70 zero width spaces, fuck you activision), so using them instead of window title is far more reliable.
- `$exec$ re.sub(r"[/\\]", "_", "v$0[title]$") $end$` will replace any slash or backslash in the window title by an underscore before inserting it, ensuring it does not get segmented into a subfolder.
